# Generated by Django 4.2.11 on 2024-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=10)),
                ('periodo', models.CharField(max_length=15)),
                ('data_criacao', models.DateField()),
            ],
        ),
    ]
