# Generated by Django 4.2.11 on 2024-04-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atitude',
            fields=[
                ('id_atitude', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('pontos', models.IntegerField()),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id_missao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('concluida', models.BooleanField()),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateField()),
                ('data_finalizacao', models.DateField()),
            ],
        ),
    ]
