# Generated by Django 4.2.11 on 2024-04-02 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_atitude_missao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('lider', models.CharField(max_length=30)),
                ('atitudes', models.ManyToManyField(blank=True, to='main.atitude')),
                ('missoes', models.ManyToManyField(blank=True, to='main.missao')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='main.turma')),
            ],
        ),
    ]
